### ISSUE TITLE
ip neigh show entries are always STALE for targets

### ISSUE THREAD

**Issue by mwolter805** [Passific/MQTT-iPhone-Tracker#7]
Hello,
Testing your project and unfortunately all targets are always not_home and could use your help troubleshooting. From the container's console the `ip neigh show` entries for the targets are always STALE. The container can reach the targets as standard pings to the targets are successful. The container's network appears to be working properly as regular state updates are received by the MQTT broker and the docker host (HAOS) has no apparent network issues. The docker host and targets are on the same subnet. 

The container is running on HAOS which is directly installed on an x64 desktop computer (not in a VM). The container was started via portainer with the following stack.

```
services:
  mqtt-iphone-tracker:
    container_name: mqtt-iphone-tracker
    hostname: mqtt-iphone-tracker
    image: ghcr.io/passific/mqtt-iphone-tracker:v1.0.11
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MQTT_USER=user
      - MQTT_PASSWORD=pw
    command: ["-t", "10.10.15.42", "mDNS Matts Phone", "-t", "10.10.15.51", "mDNS Matts Desktop", "-t", "10.10.15.46", "mDNS Moes Phone"]
```

Full container docker logs
```
Tracking 'mDNS Matts Phone' iPhone (10.10.15.42)
Tracking 'mDNS Matts Desktop' iPhone (10.10.15.51)
Tracking 'mDNS Moes Phone' iPhone (10.10.15.46)
Sat Dec 28 02:22:13 UTC 2024: Sending discovery message
Sat Dec 28 02:22:13 UTC 2024: Sending discovery message
Sat Dec 28 02:22:13 UTC 2024: Sending discovery message
```

Example `ip neigh show` entry from the container
```
10.10.15.42 dev enp0s31f6 lladdr xx:xx:xx:xx:xx:xx used 0/0/0 probes 0 STALE
```

Example standard ping from the container to the target
```
PING 10.10.15.42 (10.10.15.42): 56 data bytes
64 bytes from 10.10.15.42: seq=0 ttl=64 time=7.966 ms
64 bytes from 10.10.15.42: seq=1 ttl=64 time=101.352 ms
64 bytes from 10.10.15.42: seq=2 ttl=64 time=3.739 ms
--- 10.10.15.42 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 3.739/37.685/101.352 ms
```
